on:
  push:
    tags:
      - "autostake/v[0-9]+\\.[0-9]+\\.[0-9]+"
      - "autostake/v[0-9]+\\.[0-9]+\\.[0-9]+-rc[0-9]+"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: 'write'
      id-token: 'write'
    steps:
    - id: ver
      run: echo ::set-output name=VER::${GITHUB_REF/refs\/tags\/autostake\//}
    - uses: 'actions/checkout@v3'
    - id: auth
      uses: 'google-github-actions/auth@v0'
      with:
        token_format: access_token
        workload_identity_provider: 'projects/1020365530717/locations/global/workloadIdentityPools/github-ultrawaves/providers/github'
        service_account: 'github-actions-ultrawaves@ds-umee-hodl.iam.gserviceaccount.com'
    - uses: docker/login-action@v2
      with:
        registry: us-docker.pkg.dev
        username: oauth2accesstoken
        password: ${{ steps.auth.outputs.access_token }}
    - uses: docker/build-push-action@v3
      with:
        context: autostake
        push: true
        tags: 'us-docker.pkg.dev/ds-umee-hodl/ultrawaves/amd64/autostake:${{ steps.ver.outputs.VER }}'
